# Generated by Django 3.0.7 on 2020-06-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crud',
            options={},
        ),
        migrations.AddField(
            model_name='crud',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crud',
            name='date_agree',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='crud',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='crud',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='surname'),
        ),
    ]
