# Generated by Django 3.0.7 on 2020-06-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_auto_20200616_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud',
            name='phone',
        ),
    ]
