# Generated by Django 3.0.7 on 2020-06-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_remove_crud_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
