# Generated by Django 3.0.7 on 2020-06-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRUD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='surname')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(max_length=40, verbose_name='position')),
                ('date_agree', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
        ),
    ]
