# Generated by Django 3.0.7 on 2020-06-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_api', '0002_auto_20200623_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crud_api',
            name='date_agree',
        ),
    ]
